// <auto-generated />
using AngelsLandingv2.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AngelsLandingv2.API.Migrations.LighthouseDb
{
    [DbContext(typeof(LighthouseDbContext))]
    [Migration("20260407195406_AddMLStatusToResident")]
    partial class AddMLStatusToResident
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("CampaignName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonationType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EstimatedValue")
                        .HasColumnType("REAL");

                    b.Property<string>("ImpactUnit")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferralPostId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupporterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DonationId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.DonationAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllocationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllocationNotes")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AmountAllocated")
                        .HasColumnType("REAL");

                    b.Property<int?>("DonationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgramArea")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AllocationId");

                    b.ToTable("DonationAllocations");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.EducationRecord", b =>
                {
                    b.Property<int>("EducationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AttendanceRate")
                        .HasColumnType("REAL");

                    b.Property<string>("CompletionStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnrollmentStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ProgressPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("RecordDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchoolName")
                        .HasColumnType("TEXT");

                    b.HasKey("EducationRecordId");

                    b.ToTable("EducationRecords");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.HealthWellbeingRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Bmi")
                        .HasColumnType("REAL");

                    b.Property<bool?>("DentalCheckupDone")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EnergyLevelScore")
                        .HasColumnType("REAL");

                    b.Property<double?>("GeneralHealthScore")
                        .HasColumnType("REAL");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("REAL");

                    b.Property<bool?>("MedicalCheckupDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double?>("NutritionScore")
                        .HasColumnType("REAL");

                    b.Property<bool?>("PsychologicalCheckupDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SleepQualityScore")
                        .HasColumnType("REAL");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("HealthRecordId");

                    b.ToTable("HealthWellbeingRecords");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.HomeVisitation", b =>
                {
                    b.Property<int>("VisitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FamilyCooperationLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyMembersPresent")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("FollowUpNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationVisited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observations")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SafetyConcernsNoted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitOutcome")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitType")
                        .HasColumnType("TEXT");

                    b.HasKey("VisitationId");

                    b.ToTable("HomeVisitations");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.InKindDonationItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DonationId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EstimatedUnitValue")
                        .HasColumnType("REAL");

                    b.Property<string>("IntendedUse")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceivedCondition")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("InKindDonationItems");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.IncidentReport", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("FollowUpRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncidentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolutionDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Resolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseTaken")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .HasColumnType("TEXT");

                    b.HasKey("IncidentId");

                    b.ToTable("IncidentReports");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.InterventionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaseConferenceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanDescription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServicesProvided")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId");

                    b.ToTable("InterventionPlans");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartnerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartnerType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleType")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("PartnerId");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.PartnerAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignmentEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentStart")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgramArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsibilityNotes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("AssignmentId");

                    b.ToTable("PartnerAssignments");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.ProcessRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ConcernsFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmotionalStateEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmotionalStateObserved")
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowUpActions")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterventionsApplied")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ProgressNoted")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ReferralMade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionNarrative")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("TEXT");

                    b.HasKey("RecordingId");

                    b.ToTable("ProcessRecordings");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.PublicImpactSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Headline")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetricPayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryText")
                        .HasColumnType("TEXT");

                    b.HasKey("SnapshotId");

                    b.ToTable("PublicImpactSnapshots");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeUponAdmission")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedSocialWorker")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseControlNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentRiskLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateCaseStudyPrepared")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateClosed")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateColbObtained")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateColbRegistered")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateEnrolled")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfAdmission")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("FamilyIndigenous")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("FamilyInformalSettler")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("FamilyIs4ps")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("FamilyParentPwd")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("FamilySoloParent")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasSpecialNeeds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InitialCaseAssessment")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialRiskLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalCode")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsPwd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LengthOfStay")
                        .HasColumnType("TEXT");

                    b.Property<string>("MlLastCalculated")
                        .HasColumnType("TEXT");

                    b.Property<string>("MlPredictionStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentAge")
                        .HasColumnType("TEXT");

                    b.Property<string>("PwdType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReintegrationStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReintegrationType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Religion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialNeedsDiagnosis")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("SubCatAtRisk")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SubCatChildLabor")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SubCatChildWithHiv")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SubCatCicl")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SubCatOrphaned")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SubCatOsaec")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SubCatPhysicalAbuse")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SubCatSexualAbuse")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SubCatStreetChild")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SubCatTrafficked")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResidentId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.Safehouse", b =>
                {
                    b.Property<int>("SafehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CapacityGirls")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CapacityStaff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentOccupancy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("SafehouseCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("SafehouseId");

                    b.ToTable("Safehouses");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.SafehouseMonthlyMetric", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveResidents")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AvgEducationProgress")
                        .HasColumnType("REAL");

                    b.Property<double?>("AvgHealthScore")
                        .HasColumnType("REAL");

                    b.Property<int?>("HomeVisitationCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IncidentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonthEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("MonthStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessRecordingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MetricId");

                    b.ToTable("SafehouseMonthlyMetrics");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.SocialMediaPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AvgViewDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<double?>("BoostBudgetPhp")
                        .HasColumnType("REAL");

                    b.Property<string>("CallToActionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CampaignName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CaptionLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClickThroughs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Comments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentTopic")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DonationReferrals")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EngagementRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("EstimatedDonationValuePhp")
                        .HasColumnType("REAL");

                    b.Property<bool?>("FeaturesResidentStory")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FollowerCountAtPost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Forwards")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasCallToAction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hashtags")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Impressions")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBoosted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MentionsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumHashtags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformPostId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProfileVisits")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Reach")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Saves")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SentimentTone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Shares")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubscriberCountAtPost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VideoViews")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("WatchTimeSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("PostId");

                    b.ToTable("SocialMediaPosts");
                });

            modelBuilder.Entity("AngelsLandingv2.API.Data.Models.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionChannel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstDonationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupporterType")
                        .HasColumnType("TEXT");

                    b.HasKey("SupporterId");

                    b.ToTable("Supporters");
                });
#pragma warning restore 612, 618
        }
    }
}
